version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  reviewers:
  - forewing
  assignees:
  - forewing
